new scripts, some fixes to the docs.

diff --git a/webwml/english/ports/hurd/extra-files/cross-install b/webwml/english/ports/hurd/extra-files/cross-install
--- a/webwml/english/ports/hurd/extra-files/cross-install
+++ b/webwml/english/ports/hurd/extra-files/cross-install
@@ -61,25 +61,25 @@
 #   27 Apr 1999 - v2.0 Update package list, move perl.dist to perl (because
 #                      glibc 2.1.1 needs perl to configure, sucker!)
 #                      Copy also dpkg-hurd to ${dest}.
-#    2 Mai 1999 - v2.1 Remove base/timezones, add base/e2fsprogs.
-#    7 Mai 1999 - v2.2 Add base/grub.
+#    2 May 1999 - v2.1 Remove base/timezones, add base/e2fsprogs.
+#    7 May 1999 - v2.2 Add base/grub.
 #                      Do not ask about /usr symlink. All known problems are
 #                      resolved.
-#   13 Mai 1999 - v2.3 Add editors/ed to oplist (requested by Roland McGrath)
+#   13 May 1999 - v2.3 Add editors/ed to oplist (requested by Roland McGrath)
 #                      base/libstdc++2.9 for dselect
 #                      Replace /etc/motd with something more sensible.
-#   17 Mai 1999 - v2.4 Added syslogd and inetutils. A lot of packages are
+#   17 May 1999 - v2.4 Added syslogd and inetutils. A lot of packages are
 #                      now required which were optional before. I am not
 #                      going to take a risk. Base is base.
 #                      Add ncurses-base.
 #                      Don't do the mtab symlink. It is harmful for e2fsck.
-#   27 Mai 1999 - v2.5 Commented out some old fixes. I am going to remove
+#   27 May 1999 - v2.5 Commented out some old fixes. I am going to remove
 #                      them silently in one of the next versions.
 #                      Add /etc/hosts.
 #   15 Jun 1999 - v2.6 Add adduser.
 #   30 Jun 1999 - v2.7 Add overwrite stuff to grep, so it doesn't bail out.
 #                      Also mention that you need dpkg, sharutils and patch.
-#                      Reported by Ognyan Kulev. 
+#                      Reported by Ognyan Kulev.
 #    2 Jul 1999 - v2.8 Removed some patches. We don't want to carry around
 #                      this crap for ever.
 #   22 Jul 1999 - v3.0 Work with perl5, add libgdbmg1.
@@ -101,19 +101,52 @@
 #                      Remove locales.
 #    1 Mar 2000	- v4.3 Various updates.
 #    1 Apr 2000 - v4.4 libreadlineg2 in oldlibs now.
+#    8 Aug 2000 - v5.0 Changes by Santiago da Vila:
+#
+# * "download" is now a URL containing *everything* but dists/unstable/...
+# Both ftp:// and http:// are allowed (since it's wget who does it).
+#
+# * Downloaded packages are kept in .../partial, I can provide a script
+# to update the repository using the retrieved files if this an absolute
+# requirement, but I don't think cross-install should become a do-it-all
+# script. Also, the Packages.gz file which is used to guess the package
+# filename is kept in .../partial, this is to not override whatever
+# existing Packages.gz in the repository.
+#
+# * Changelog: s/Mai/May/
+#
+# * Removed section names from plist.
+#
+# * New variable dpkghurdoptions="--force-depends --force-overwrite"
+#   This is just to improve readability in dpkg command line (it was
+#   too large).
+#
+# * LANG=C (maybe the right thing to do here is LC_ALL=C, do not remember
+# which one overrides the other, sorry).
+#
+# * Added libdb2 to plist, it's needed by perl-5.005-base.
+# 
+# * Introduced a shell function, cross_install(), it is used twice, one
+# for the packages in plist, and another one for packages in oplist.
+# This is to avoid code duplication. (BTW: For this function I've used
+# 2-space tabs, feel free to put real tabs again :-)
+#
+#			Also add libstdc++2.10 (we'll need it)
 
-plist="base/adduser base/ae base/base-files base/base-passwd base/bash \
-       base/bsdutils base/debianutils base/diff base/dpkg-ftp \
-       base/dpkg-mountable base/dpkg base/e2fsprogs \
-       base/fileutils base/findutils base/gettext-base base/gnumach
-       base/grep base/grub base/gzip base/hostname base/hurd
-       net/inetutils base/libc0.2 base/libgdbmg1 base/libncurses5 \
-       base/libnet-perl oldlibs/libreadlineg2 base/libstdc++2.9 \
-       base/libwrap0 base/mawk base/ncurses-base base/ncurses-bin \
-       base/passwd base/perl-5.005-base base/perl-base base/sed \
-       base/shellutils base/slang1 base/syslogd base/tar base/tcpd \
-       base/textutils interpreters/perl-5.005 oldlibs/libncurses4"
-oplist="text/less editors/ed"
+plist="adduser ae base-files base-passwd bash
+       bsdutils debianutils diff dpkg-ftp
+       dpkg-mountable dpkg e2fsprogs
+       fileutils findutils gettext-base gnumach
+       grep grub gzip hostname hurd
+       inetutils libc0.2 libgdbmg1 libncurses5
+       libnet-perl libreadlineg2 libstdc++2.9
+       libstdc++2.10
+       libwrap0 mawk ncurses-base ncurses-bin
+       passwd libdb2 perl-5.005-base perl-base sed
+       shellutils slang1 syslogd tar tcpd
+       textutils perl-5.005 libncurses4"
+
+oplist="less ed"
 #oplist=""
 
 # If you only want a minimal base system, leave out packages listed in
@@ -127,18 +160,23 @@ oplist="text/less editors/ed"
 #  ./cross-install /gnu
 # where /gnu is the mount point of your hurd partition.
 
-
 #
 # CONFIGURATION
 #
 hostname="hurd"
 domainname="hurdnet.org"
 dpkghurd="`pwd`/dpkg-hurd"
+dpkghurdoptions="--force-depends --force-overwrite"
 nativeinstall="`pwd`/native-install"
 log="`pwd`/install.log"
-download=""
+download="ftp://ftp.de.debian.org/pub/debian"
+dist="sid"
+arch="hurd-i386"
 dest=""
 repository="`pwd`"
+
+LANG=C
+LC_ALL=C
 
 while [ "$#" -ne 0 ]
 do
@@ -205,8 +243,51 @@ err ()
     exit 1
 }
 
+###########################
+# function cross_install()
+###########################
+
+cross_install() {
+  pname=$1
+  whatifnot=$2
+
+  package=`find ${repository} -name "${pname}_*.deb" 2> /dev/null | tail -n 1`
+  matches=`find ${repository} -name "${pname}_*.deb" 2> /dev/null | wc -l`
+  if [ ${matches} = 0 ] ; then
+    if ! [ -z "$download" ]; then
+      echo "- ${pname} not found, downloading from ${download}."
+      mkdir -p ${repository}/partial
+      if [ ! -f ${repository}/partial/Packages.gz ]; then
+        wget -cP ${repository}/partial ${download}/dists/${dist}/main/binary-${arch}/Packages.gz
+      fi
+      filename=`zcat ${repository}/partial/Packages.gz | awk -vp=$pname '
+        $0 ~ "^Package:" { package = $2 }
+        $0 ~ "^Filename:" && p == package { print $2 }'`
+      wget --retr-symlinks -cP ${repository}/partial ${download}/$filename
+      package=`find ${repository} -name "${pname}_*.deb" 2> /dev/null | tail -n 1`
+      matches=`find ${repository} -name "${pname}_*.deb" 2> /dev/null | wc -l`
+    fi
+  fi
+
+  if [ ${matches} = 0 ] ; then
+    if [ "${whatifnot}" = "error" ]; then
+      echo - ${pname} could not be found, but it is needed
+      exit 1
+    else
+      echo - ${pname} could not be found, let us hope it is not vital
+    fi
+  else
+    if [ ${matches} != 1 ] ; then
+      echo "More than one version of package ${pname} available, choosing the alphabetically last."
+    fi
+    echo - $package
+    ${dpkghurd} --unpack $package $dpkghurdoptions >> ${log} 2>&1 || break
+  fi
+}
+
+
 #############################
-# Comply to Hurd philosophy.
+# Comply with Hurd philosophy.
 #############################
 
 if [ ! -e ${dest}/usr ] ; then
@@ -244,78 +325,16 @@ echo
 echo "Installing necessary packages, this may take some time."
 
 cd ${dest}
-for pname in ${plist}
+for p in ${plist}
 do
-	package=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | tail -n 1`
-	matches=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | wc -l`
-
-	if [ ${matches} = 0 ] ; then
-		newpname=`basename ${pname}`
-		package=`ls -1 ${repository}/${newpname}_*.deb 2> /dev/null | tail -n 1`
-		matches=`ls -1 ${repository}/${newpname}_*.deb 2> /dev/null | wc -l`
-	fi
-
-	if [ ${matches} = 0 ] ; then
-		if ! [ -z "$download" ]; then
-			echo "- ${pname} not found, downloading from ${download}."
-			mkdir -p ${repository}/partial
-			wget --retr-symlinks -cqP ${repository}/partial ftp://${download}/debian/dists/unstable/main/binary-hurd-i386/${pname}_\*.deb
-			mkdir -p ${repository}/`dirname ${pname}`
-			mv ${repository}/partial/`basename ${pname}`_*.deb ${repository}/`dirname ${pname}`
-			package=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | tail -n 1`
-			matches=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | wc -l`
-		fi
-	fi
-
-	pname=`basename $pname`
-
-	if [ ${matches} = 0 ] ; then
-		echo - ${pname} could not be found, but it is needed.
-		exit 1
-	else
-		if [ ${matches} != 1 ] ; then
-			echo "More than one version of package ${pname} available, choosing the alphabetically last."
-		fi
-		echo - ${package}
-		${dpkghurd} --unpack ${package} --force-depends --force-overwrite >> ${log} 2>&1 || break
-	fi
+    cross_install $p "error"
 done
+
 echo
 echo "Installing optional packages, this may take some time."
-for pname in ${oplist}
+for p in ${oplist}
 do
-	package=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | tail -n 1`
-	matches=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | wc -l`
-
-	if [ ${matches} = 0 ] ; then
-		newpname=`basename ${pname}`
-		package=`ls -1 ${repository}/${newpname}_*.deb 2> /dev/null | tail -n 1`
-		matches=`ls -1 ${repository}/${newpname}_*.deb 2> /dev/null | wc -l`
-	fi
-
-	if [ ${matches} = 0 ] ; then
-		if ! [ -z "$download" ]; then
-			echo "- ${pname} not found, downloading from ${download}."
-			mkdir -p ${repository}/partial
-			wget --retr-symlinks -cqP ${repository}/partial ftp://${download}/debian/dists/unstable/main/binary-hurd-i386/${pname}_\*.deb
-			mkdir -p ${repository}/`dirname ${pname}`
-			mv ${repository}/partial/`basename ${pname}`_*.deb ${repository}/`dirname ${pname}`
-			package=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | tail -n 1`
-			matches=`ls -1 ${repository}/${pname}_*.deb 2> /dev/null | wc -l`
-		fi
-	fi
-
-	pname=`basename $pname`
-
-	if [ ${matches} = 0 ] ; then
-		echo "- ${pname} could not be found, let us hope it is not vital."
-	else
-		if [ ${matches} != 1 ] ; then
-			echo "More than one version of package ${pname} available, choosing the alphabetically last."
-		fi
-		echo - ${package}
-		${dpkghurd} --unpack ${package} --force-depends --force-overwrite >> ${log} 2>&1 || break
-	fi
+    cross_install $p "warning"
 done
 
 set +e
@@ -324,10 +343,13 @@ set -e
 
 if [ ! "x${errors}" = x ] ; then
 	echo
-	echo "ERROR: dpkg did return unusual messages, please investigate:"
-	echo "INSTALLATION ABORTED!"
+	echo 'ERROR: dpkg did return unusual messages, please investigate:'
+	echo 'INSTALLATION ABORTED!'
 	echo
 	grep -v '^rm: /tmp/.*: Device or resource busy$\|dpkg - warning, overriding problems\|trying to override\|Preparing to replace\|Unpacking\|pre-dependency problem\|Selecting previously deselected package\|pre-depends on\|overriding problem because --force enabled\|(Reading database ...\| package architecture (hurd-i386) does not match system\|is not installed.\|but has never been configured.\|dpkg-deb: building package' ${log}
+	echo
+	echo 'INSTALLATION ABORTED because of unknown errors. Partial installation'
+	echo 'is NOT usable. Correct the error and start from scratch.'
 	exit 1
 fi
 
@@ -446,7 +468,7 @@ echo
 echo "Preparing /etc/resolv.conf."
 
 if [ -e /etc/resolv.conf ] ; then
-	echo Copying this machines resolv.conf to the Hurd partition.
+	echo Copying this machine\'s resolv.conf to the Hurd partition.
 	echo If this is not correct, please edit.
 	cp /etc/resolv.conf ${dest}/etc/resolv.conf
 else
