Redirect error messages to lessoften.log.

diff --git a/cron/lessoften b/cron/lessoften
--- a/cron/lessoften
+++ b/cron/lessoften
@@ -7,7 +7,7 @@ umask 002
 
 # locking
 if lockfile -! -l 43200 -r 0 "$crondir/lessoften.lock"; then
-  echo `hostname` is unable to start update, lock file exists.
+  echo `hostname` is unable to start update, lock file exists. >> $crondir/lessoften.log
   exit 1
 fi
 trap "rm -f $crondir/lessoften.lock" exit
@@ -42,7 +42,7 @@ cp -af $webtopdir/bf/woody/boot-floppies/documentation/arch/* $webdir/releases/w
 # previously in parts/1l10ndata, from bouz
 cd $crondir/datafiles/
 echo "updating the database file used to display l10n stats..." >> $crondir/lessoften.log
-wget -q -N http://people.debian.org/~pmachard/l10n/material/data/unstable.gz || { echo "couldn't fetch data/unstable on gluck!"; exit 1; }
+wget -q -N http://people.debian.org/~pmachard/l10n/material/data/unstable.gz || { echo "couldn't fetch data/unstable!" >> $crondir/lessoften.log; exit 1; }
 gunzip -c -f unstable.gz > unstable.gluck
 ln -sf $crondir/datafiles/unstable.gluck $webtopdir/webwml/english/international/l10n/data/unstable.gluck
 
