ftp-master -> gluck, from bouz

diff --git a/cron/lessoften b/cron/lessoften
--- a/cron/lessoften
+++ b/cron/lessoften
@@ -42,9 +42,9 @@ cp -af $webtopdir/bf/woody/boot-floppies/documentation/arch/* $webdir/releases/w
 # previously in parts/1l10ndata, from bouz
 cd $crondir/datafiles/
 echo "updating the database file used to display l10n stats..." >> $crondir/lessoften.log
-wget -q -N http://ftp-master.debian.org/~barbier/l10n/material/data/unstable.gz || { echo "couldn't fetch data/unstable on ftp-master!"; exit 1; }
-gunzip -c -f unstable.gz > unstable.ftp-master
-ln -sf $crondir/datafiles/unstable.ftp-master $webtopdir/webwml/english/international/l10n/data/unstable.ftp-master
+wget -q -N http://gluck.debian.org/~barbier/l10n/material/data/unstable.gz || { echo "couldn't fetch data/unstable on gluck!"; exit 1; }
+gunzip -c -f unstable.gz > unstable.gluck
+ln -sf $crondir/datafiles/unstable.gluck $webtopdir/webwml/english/international/l10n/data/unstable.gluck
 
 echo "updating the non-US database file used to display l10n stats..." >> $crondir/lessoften.log
 wget -q -N http://non-us.debian.org/~barbier/l10n/material/data/unstable.gz || { echo "couldn't fetch data/unstable on non-us!"; exit 1; }
@@ -56,7 +56,7 @@ rm -f unstable.gz
 
 echo "extracting the list of languages..." >> $crondir/lessoften.log
 cd $webtopdir/webwml/english/international/l10n
-./scripts/list-languages.pl data/unstable.ftp-master data/unstable.non-US > data/langs
+./scripts/list-languages.pl data/unstable.gluck data/unstable.non-US > data/langs
 
 # the below scripts will echo what they are doing themselves
 $crondir/people_scripts/update.packages+sources >> $crondir/lessoften.log
